name: Publish Dart Package

on:
  push:
    branches:
      - main
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
    uses: dart-lang/setup-dart/.github/workflows/publish.yml@v1

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Dart
        uses: dart-lang/setup-dart@v1.2
        with:
          sdk: stable

      - name: Install Dependencies
        run: dart pub get

      - name: Publish to pub.dev
        run: dart pub publish --force
