name: Publish Dart Package

on:
  push:
    branches:
      - main

jobs:
  prep:
    runs-on: ubuntu-latest

    outputs:
      version: ${{ steps.get_version.outputs.VERSION }}
      skip: ${{ steps.check_tag.outputs.SKIP }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get Version from pubspec.yaml
        id: get_version
        run: |
          VERSION=$(grep 'version: ' pubspec.yaml | sed 's/version: //')
          echo "Extracted version: $VERSION"
          echo "::set-output name=VERSION::$VERSION"

      - name: Check if Tag Exists
        id: check_tag
        run: |
          if git rev-list -q v${{ steps.get_version.outputs.VERSION }}; then
            echo "Tag v${{ steps.get_version.outputs.VERSION }} already exists. Skipping tag creation."
            echo "::set-output name=SKIP::true"
          else
            echo "Tag does not exist. Proceeding with tag creation."
            echo "::set-output name=SKIP::false"
          fi

  publish:
    needs: prep
    if: needs.prep.outputs.skip == 'false'
    uses: dart-lang/setup-dart/.github/workflows/publish.yml@v1

  tag:
    needs: prep
    if: needs.prep.outputs.skip == 'false'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Create and Push Tag
        run: |
          git tag v${{ needs.prep.outputs.version }}
          git push origin v${{ needs.prep.outputs.version }}
